import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>shortener-url</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <h1>Welcome to OSBIT Shortener URL</h1>
      <p>Try changes the url to see what will happen</p>
      <p>URL:</p>
      <p>1. /Youtube</p>
      <p>2. /instagaram</p>
      <p>3. /facebook</p>
    </>
  );
};

export default Index;